### ISSUE TITLE
Temporary log files not written to tempDir

### ISSUE THREAD

**Issue by bitsgalore** [KBNLresearch/iromlab#33]
Applies to all wrapper modules. Solution is to change this:

    logFile = ''.join([config.tempDir,shared.randomString(12),".log"])

into:
    
    logFile = os.path.join(config.tempDir,shared.randomString(12) + ".log")

**Comment by WillemJan** [comment]
Why not use os.tmpfile() and let the os do the moppig for you?

Anyhoe my 5 cents ;)

Johan van der Knijff schreef op 2017-02-24 15:25:

**Comment by bitsgalore** [comment]
Good thinking, but apparently on Windows os.tmpfile() only works if the script is run as admin:

<http://stackoverflow.com/questions/7807855/os-tmpfile-doesnt-work-under-windows>

As this software will *only* be run under Windows (and most likely not as admin) I'd rather not use this.

**Comment by WillemJan** [comment]
some osses I never got the gist of ;)

Johan van der Knijff schreef op 2017-02-24 17:53:

**Comment by bitsgalore** [comment]
Fixed: <https://github.com/KBNLresearch/iromlab/commit/a0cb88c0bd4e7b399a9b34eef730de8086bd502c>
