### ISSUE TITLE
Get rid of Carrier Type field

### ISSUE THREAD

**Issue by bitsgalore** [KBNLresearch/iromlab#66]
Reasons:

- Current manual entry of *carrierType* in Iromlab is prone to entry errors, 
- For an Iromlab operator, establishing the actual carrier type from the physical media is not always straightforward (e.g. cd-rom vs cd-video; cd-roms that turn out to contain audio, etc.)
- The *actual* carrier type is already established automatically and unambiguously by cd-info.

If we drop it altogether, volumeNumber sequence will simply cover all carriers that are part of a PPN (no grouping based on carrier type). 

Related to:

<https://github.com/KBNLresearch/iromlab/issues/67>

**Comment by bitsgalore** [comment]
Addition/correction:

> The actual carrier type is already established automatically and unambiguously by cd-info

Not if the carrier is a DVD, which shows up as "CD-ROM with unknown filesystem" in analysis report (CD-ROMs with HFS+ FS also give this result)!!

So maybe it's better to keep the Carrier Type entry field.

**Comment by robdebruin** [comment]
Even though the type detection might not be 100% proof, it would at least be useful to give the user a hint. I now find myself checking on a regular basis if an optical carrier is cd-rom or audio.

**Comment by bitsgalore** [comment]
@robdebruin  I think the solution here is that the "final" establishment of the carrier type should be done further down the processing chain (i.e. outside of Iromlab). Typically this would be at the SIP creation stage. For example, the combined values  of the *containsAudio*, *containsData*, and *cdExtra* fields (derived from *cd-info*), and the *isoBuster* output (if it exists) should allow a SIP creation tool to establish the carrier type pretty much unambiguously for all cases I can think of. If so, there would be no need for the error-prone manual entry. But there might be some weird edge cases I'm overlooking for which a manually added classification would actually be helpful.

**Comment by bitsgalore** [comment]
Done: <https://github.com/KBNLresearch/iromlab/commit/5e8b597016e0a9c8bb7dd580c32f8306fa156710>
