### ISSUE TITLE
Keep track of number of discs in batch and show as counter in GUI

### ISSUE THREAD

**Issue by bitsgalore** [KBNLresearch/iromlab#71]
As requested by RdB.

**Comment by robdebruin** [comment]
Also ... but this is tied in with the volume number, show the added PPN's and the amount of volumes added.

**Comment by bitsgalore** [comment]
This info is now written to log + console:

<https://github.com/KBNLresearch/iromlab/commit/6fb625bb53eb937601bdc11e34e6b76415712667>
<https://github.com/KBNLresearch/iromlab/commit/8d940e8cdb9ec5bcf3046c6a58556cfd4880ac36>
