### ISSUE TITLE
Submit without PPN does not give error message

### ISSUE THREAD

**Issue by robdebruin** [KBNLresearch/iromlab#89]
When no PPN is given, when PPN is enabled, does not give an error message. Instead it continuous en adds the default / random MDO detail record. 

Expected: error message and submit fails.

**Comment by bitsgalore** [comment]
Yes, I came across that one myself earlier this week! Already fixed by checking if entered PPN is an empty string: <https://github.com/KBNLresearch/iromlab/commit/2fd0498df3692940786ed5c2167ca2f34636e2a4>
